# The ProfitabilityMetrics class contains methods to calculate various profitability metrics such as
# gross profit percent, profit before tax, net profit margin, return on assets, return on equity, and
# operating profit.
class ProfitabilityMetrics:
    
    def __init__(self):
        pass
    
    
    def gross_profit_percent(self,total_rev, cgs):
        """
        The function calculates the gross profit percentage by dividing the total revenue by the cost of
        goods sold.
        
        :param total_rev: The total revenue generated by a business or company
        :param cgs: CGS stands for Cost of Goods Sold. It refers to the direct costs incurred in
        producing or acquiring the goods that a company sells. This includes the cost of materials,
        labor, and other direct costs associated with producing the goods
        :return: the gross profit percent, which is calculated by dividing the total revenue by the cost
        of goods sold (cgs).
        """
        return total_rev/cgs
    
    def profit_pretax(self,net_income, total_rev):
        """
        The function calculates the pretax profit by dividing the net income by the total revenue.
        
        :param net_income: Net income refers to the total amount of money a company earns after
        deducting all expenses and taxes. It is a measure of the company's profitability
        :param total_rev: The total revenue generated by a company or business before any expenses or
        taxes are deducted
        :return: the pretax profit, which is calculated by dividing the net income by the total revenue.
        """
        return net_income / total_rev

    
    def percent_profit_pretax_to_tassets(self, pr_pretax, total_assets):
        """
        The function calculates the percentage profit before tax to total assets ratio.
        
        :param pr_pretax: The parameter "pr_pretax" represents the pre-tax profit, which is the profit
        earned by a company before taxes are deducted
        :param total_assets: The total assets refers to the total value of all the assets owned by a
        company. This includes both tangible assets (such as buildings, equipment, and inventory) and
        intangible assets (such as patents, trademarks, and goodwill). It is a measure of the company's
        financial strength and can be found
        :return: the percentage of pre-tax profit to total assets.
        """
        return pr_pretax / total_assets
        
    
    def percent_profit_pretax_to_networth(self,pr_pretax, net_worth):
        """
        The function calculates the percentage of profit before tax relative to net worth.
        
        :param pr_pretax: The parameter "pr_pretax" represents the pre-tax profit, which is the profit
        earned before any taxes are deducted
        :param net_worth: Net worth refers to the total value of a person's assets minus their
        liabilities. It is a measure of an individual's financial health and can include things like
        cash, investments, real estate, and other valuable possessions
        :return: the percentage of pre-tax profit to net worth.
        """
        return pr_pretax / net_worth

    
    def net_profit_margin(self, net_pr, total_rev):
        """
        The function calculates the net profit margin by dividing the net profit by the total revenue
        and multiplying by 100.
        
        :param net_pr: The net_pr parameter represents the net profit, which is the total revenue minus
        all expenses and taxes. It is the amount of money left over after all costs have been deducted
        from the total revenue
        :param total_rev: The total revenue generated by the company
        :return: The net profit margin, calculated as the net profit divided by the total revenue,
        multiplied by 100.
        """
        return net_pr * 100 /total_rev

    
    def return_on_assets(self,net_pr, total_ass):
        """
        The function calculates the return on assets by dividing the net profit by the total assets and
        multiplying by 100.
        
        :param net_pr: The net profit of a company, which is the total revenue minus all expenses and
        taxes. It represents the company's profitability
        :param total_ass: The parameter "total_ass" represents the total assets of a company
        :return: The return on assets, calculated as the net profit divided by the total assets,
        multiplied by 100.
        """
        return net_pr * 100 / total_ass

    
    def return_on_equity(self, net_pr, net_worth):
        """
        The function calculates the return on equity by dividing the net profit by the net worth and
        multiplying by 100.
        
        :param net_pr: Net profit after tax
        :param net_worth: Net worth refers to the total assets minus total liabilities of a company. It
        represents the value of the company's equity or ownership
        :return: The return on equity, calculated as the net profit divided by the net worth, multiplied
        by 100.
        """
        return net_pr * 100 / net_worth
        
    
    def operating_profit(self, operating_rev, total_rev):
        """
        The function calculates the operating profit as a percentage of the total revenue.
        
        :param operating_rev: The operating revenue, which is the total revenue generated from the core
        operations of a business. This includes revenue from sales of goods or services
        :param total_rev: The total revenue generated by the company
        :return: the operating profit as a percentage of the total revenue.
        """
        return operating_rev * 100 / total_rev
    
        